### ISSUE TITLE
touch up the friend's list aesthetic. 

### ISSUE THREAD

**Issue by aaronm-2112** [AzureDoritos/Pace-Pal#40]
Not the recycler view where the friends are listed, or the friend presentation on the list, but the magnifying glass and the refresh button are looking pretty ugly right now.

**Comment by JetSetDoritos** [comment]
Also add a FriendProfileFragment, right now selecting a friend just displays a toast and does nothing.

**Comment by aaronm-2112** [comment]
> Also add a FriendProfileFragment, right now selecting a friend just displays a toast and does nothing.

great idea! I'll  make that another issue though cuz using issues and showing that we used them is going to be a small part of our grade on the presentation.
