### ISSUE TITLE
More Sign In Info to DB

### ISSUE THREAD

**Issue by aaronm-2112** [AzureDoritos/Pace-Pal#8]
When user signs in we want to send more information (username, password, id, etc) to the firestore database to be accessed when needed.

**Comment by aaronm-2112** [comment]
Next Step is to fix small issues. User can hit submit to get to the main menu without having a profile in the authentication database. User can hit submit before filling all of the required fields. Will make sure user cannot enter the menu without filling in all fields, and without having successfully signed in or passing a check to see if they have an account in the authentication database.
I'll work on this stuff.

**Comment by JetSetDoritos** [comment]
oh ha thats an oversight 😅

**Comment by aaronm-2112** [comment]
Okay this hasn't fixed the second issue yet, I don't believe, but improving the login flow and fixing all bugs is a different issue I think. Do we have all the information we need to continue with the database session creation? If so, we can close this issue I think.
